### ISSUE TITLE
Instruction to run on base containers

### ISSUE THREAD

**Issue by grillorafael** [tofutf/tofutf#158]
Hi!

I'm looking for instructions of how to run this using plain containers (i.e. just play docker / ECS / Fargate / etc) instead of helmcharts. Is there an instruction for is somewhere in this repo ? I couldn't find it myself so thats why I'm creating this issue.

Happy to contribute if needed

**Comment by grillorafael** [comment]
Perhaps a docker-compose based example would be helpful as well!

**Comment by robbert229** [comment]
Hello @grillorafael, right now there aren't any specific instructions for running tofutf on a plain container. 

Technically you can do this pretty easily at the moment, the container is here: `ghcr.io/tofutf/tofutf/tofutfd:v0.9.1`, and the docs for configuration are here: 
* https://docs.tofutf.io/config/flags
* https://docs.tofutf.io/config/envvars

I would like to keep the project as lean as possible and would like to avoid supporting multiple deployment strategies as much as possible. I am open to accepting documentation enhancements from the community regarding this, but don't think I have the time to support it as a first-class feature.

**Comment by grillorafael** [comment]
Thanks! I’ll give it a try. Our plan is to try to setup a simple deployment with docker compose to test locally and then have it running in ECS. Thanks!

**Comment by krlmlr** [comment]
@grillorafael: Was this deployment successful? Did you encounter any issues worth mentioning? Thanks!

**Comment by grillorafael** [comment]
Hi @krlmlr we are running currently in ECS and everything is running smoothly
