### ISSUE TITLE
VCS triggers example pattern is misleading

### ISSUE THREAD

**Issue by kjohnston-vetro** [tofutf/tofutf#232]
**Describe the bug**

![image](https://github.com/tofutf/tofutf/assets/79098866/ff303b67-7064-43ca-b145-a94e26422360)

When setting up trigger patterns in VCS triggers, the example path in the input field includes a leading `/`—`/modules`. I assumed the leading `/` represented the root of the VCS repo.

Experimenting with this feature, though, I was unable to get it work with a leading `/`. Filepaths needed to omit the leading `/` to trigger runs.

** TofuTF Version**
0.9.1

**To Reproduce**

Go to a workspace that is connected to VCS and select "Only trigger runs when files in specified paths change" from the VCS triggers section. The example text in the input field includes a leading `/` which doesn't work in practice.

**Expected behavior**
The example text in the input field should make clear that the filepath for run triggers should not include a leading `/`

**Screenshots**

![image](https://github.com/tofutf/tofutf/assets/79098866/ff303b67-7064-43ca-b145-a94e26422360)

**Browser:**
 - Browser firefox
 - Version 127.0.1

**Additional context**
None

**Comment by robbert229** [comment]
@kjohnston-vetro fix inbound! Thanks for the bug report.
