### ISSUE TITLE
Please issue a new release

### ISSUE THREAD

**Issue by raspbeguy** [tofutf/tofutf#239]
Hello, I'm currently working on packaging tofutf on Alpine Linux. I would appreciate a new release based on current master, as it would fix a lot of issues that are present in last release (0.9.1). For instance broken checks due to renaming from otf to tofutf, and probably much more, but I don't encountered them yet.

By the way, is there a chat (IRC/Matrix/whatever) dedicated to tofutf?

Thanks for your attention.

EDIT: This isn't a bug report, but I can't delete the label from the issue.

**Comment by robbert229** [comment]
no worries, 

I am actually prepping a release this week. I will ping you when its out.

**Comment by robbert229** [comment]
Just a small update. I haven't forgotten about the release. I have been squashing some bugs and doing some updates, but you can expect the release in a couple of days.

**Comment by grillorafael** [comment]
Hey @robbert229 ! Just checking in on this. Anything we can help ?

**Comment by robbert229** [comment]
I am working on squashing a bug I introduced before release. I am nearly
there. :)

**Comment by robbert229** [comment]
@raspbeguy @grillorafael v0.10.0 is out! Thank you for your patience.
